const SERVICE_SETUP_SCREEN_NAME = 'SERVICE_SETUP_SCREEN_NAME';
const SERVICE_SETUP_SCREEN_METHOD = 'SERVICE_SETUP_SCREEN_METHOD';
const SERVICE_SETUP_SCREEN_NATURAL = 'SERVICE_SETUP_SCREEN_NATURAL';

const setupScreens = {
  SERVICE_SETUP_SCREEN_NAME,
  SERVICE_SETUP_SCREEN_METHOD,
  SERVICE_SETUP_SCREEN_NATURAL,
};

export default setupScreens;
