export const SERVICE_SETUP_SCREEN_NAME = 'SERVICE_SETUP_SCREEN_NAME';
export const SERVICE_SETUP_SCREEN_METHOD = 'SERVICE_SETUP_SCREEN_METHOD';
export const SERVICE_SETUP_SCREEN_NATURAL = 'SERVICE_SETUP_SCREEN_NATURAL';
export const SERVICE_SETUP_SCREEN_SPREADSHEET = 'SERVICE_SETUP_SCREEN_SPREADSHEET';
export const SERVICE_SETUP_SCREEN_DEVICE = 'SERVICE_SETUP_SCREEN_DEVICE';
